#!/usr/bin/env bash
# Redirects
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/stylebitt.com;}' /etc/nginx/sites-available/default
service nginx restart
