#!/usr/bin/env bash
# This script just does it

echo $$ > /var/run/myscript.pid

terminate() {
  echo "I hate the kill command"
}

interrupt() {
  echo "Y U no love me?!"
}

quit_terminate() {
  rm /var/run/myscript.pid
  exit
}

trap 'terminate' SIGTERM
trap 'interrupt' SIGINT
trap 'quit_terminate' SIGQUIT SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 1
done
