#!/usr/bin/env bash
# This script is displaying your bash pid

processes=$(pgrep bash)
for process in $processes; do
    process_name=$(cat /proc/"$process"/comm)
    echo "$process $process_name"
done
