#!/usr/bin/env bash
# This script is displaying your bash pid

for pid_dir in /proc/*; do
    pid=$(basename "$pid_dir")
    if [ -e "/proc/$pid/cmdline" ]; then
        process_name=$(tr -d '\0' < "/proc/$pid/cmdline")
        if [[ "$process_name" == "bash"* ]]; then
            echo "$pid $process_name"
        fi
    fi
done
