#!/usr/bin/env bash
# This script is displaying To infinity and beyond indefinitely.

invincible() {
	printf "I am invincible!!!\n"
}
while (true)
do
	printf "To infinity and beyond\n"
	trap invincible SIGTERM
	sleep 2
done
