#!/usr/bin/env bash
# This script is displaying current directory without first -

shopt -s nullglob
for file in *; do
    if [[ -f $file && ! $file =~ ^\. ]]; then
        name_after_dash="${file#*-}"
        echo "$name_after_dash"
    fi
done
