#!/usr/bin/env bash
# This script changes IPs
cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" >> ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
sudo sh -c cp ~/hosts.new /etc/hosts
rm ~/hosts.new
